### ISSUE TITLE
The website is not responsive so can I make it responsive

### ISSUE THREAD

**Issue by Vishal2002** [seths10/Quotes-Generator#102]
The quote generator website is not responsive.

**Comment by Vishal2002** [comment]
Hey, @seths10 Can you assign me this issue to work under Hacktoberfest 2022.

**Comment by Vishal2002** [comment]
Please assign me to work on this

**Comment by seths10** [comment]
I'm still waiting for a PR

**Comment by Vishal2002** [comment]
Please merge my PR

**Comment by seths10** [comment]
Done
