### ISSUE TITLE
Tweet this button 

### ISSUE THREAD

**Issue by akashyap25** [seths10/Quotes-Generator#13]
Tweeter opens directly when website is opened,  but tweet this button doesn't work when clicked .

**Comment by akashyap25** [comment]
Please assign me this  under hacktoberfest tag , I can work on this.

**Comment by seths10** [comment]
I have assigned you to the issue, submit a PR and I will add the hacktoberfest tag after review

**Comment by seths10** [comment]
This issue has been handled by another person
