### ISSUE TITLE
Updating Mentions of Twitter in the Code and Front end to use X Instead

### ISSUE THREAD

**Issue by Pasqua101** [seths10/Quotes-Generator#188]
Hello, I would like to modify some of the code in the front end and back end to mention X instead of Twitter. Since there has now been the name change of the platform. For example, the "Tweet This" button on the website would say "Post This" with the X logo instead of the Twitter logo.  If allowed, I would also like to change the name of variables or functions in the script.js file to say X or post instead of Tweet. Although, the URL to make a post would remain the same as Twitter has not changed their URL to use X. 

I know this issue isn't related to what is stated in the contributing.md file, but I would like to make these changes to the code if it is allowed. If this is allowed, can the Hacktoberfest label be added? Thanks in advanced.

**Comment by seths10** [comment]
@Pasqua101 you can proceed to make the requested changes

**Comment by Pasqua101** [comment]
Thank you. I'll get to work.

**Comment by Pasqua101** [comment]
Hey @seths10 , just working on the issue and I'm experiencing a problem on my end. Almost, done but I'm struggling with using the logo for X. For some reason, I can't get this line of code for the logo to work with me, `<i class="fa-brands fa-square-x-twitter fa-lg"></i>`. However, if I use it as an svg, like so `<svg xmlns="http://www.w3.org/2000/svg" height="1.25em" viewBox="0 0 448 512"><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M64 32C28.7 32 0 60.7 0 96V416c0 35.3 28.7 64 64 64H384c35.3 0 64-28.7 64-64V96c0-35.3-28.7-64-64-64H64zm297.1 84L257.3 234.6 379.4 396H283.8L209 298.1 123.3 396H75.8l111-126.9L69.7 116h98l67.7 89.5L313.6 116h47.5zM323.3 367.6L153.4 142.9H125.1L296.9 367.6h26.3z"/></svg>`  I can get the icon to display just fine. Got any idea of what I might be doing wrong? I would use the SVG, but it doesn't properly sync the color when the user switches between light and dark mode. Also, in case you need it, I am getting the logo from [here](https://fontawesome.com/icons/square-x-twitter?f=brands&s=solid&sz=lg).

**Comment by seths10** [comment]
I think you should be able to change the color from the `svg` link to something neutral

**Comment by Pasqua101** [comment]
Hey @seths10, sorry for taking so long. Probably would've had this done within an hour or two, but my ISP experienced an outage last night so I called it a day. I made the PR, but I wasn't able to change the colour of the SVG to be something neutral. I ended up making 2 SVG files with different colours. Let me know what you think.

**Comment by seths10** [comment]
I've seen it

**Comment by Pasqua101** [comment]
Awesome, thank you!
