### ISSUE TITLE
Light Mode feature

### ISSUE THREAD

**Issue by seths10** [seths10/Quotes-Generator#19]
The site is already in dark mode, I need someone to be able to implement the light mode feature upon toggle of a button preferably at the top of the page

**Comment by xOluwaseyi** [comment]
Hi Seths10, can I get a link to the current live version?

**Comment by xOluwaseyi** [comment]
Hi @seths10 , please assign this issue to me. Thank you!

**Comment by KaranSapra124** [comment]
I can help you out on this, assign this project to me

**Comment by xOluwaseyi** [comment]
You can review it now. @seths10
