### ISSUE TITLE
Add More Quotes

### ISSUE THREAD

**Issue by seths10** [seths10/Quotes-Generator#2]
Hi 👋,

Please go ahead and add more quotations to the `quotes.js` file under the `js` folder.

🎯 Goal
To get more quotations on the website

Please make sure your PR passes the following:

- [ ] PR contains not more than 10 quotes.
- [ ] Quote is not already in the file.

**Comment by bruceyboy86** [comment]
Happy hacktoberfest! Can I be assigned this issue please? :)

**Comment by STM3900** [comment]
Hello, can I help too? :)

**Comment by Irjean** [comment]
Hello, can I assist too? :)

**Comment by InsightCracker** [comment]
Can I add more

**Comment by seths10** [comment]
contribution is welcomed

**Comment by seths10** [comment]
> Happy hacktoberfest! Can I be assigned this issue please? :)

you can go ahead and add more, submit a pull request and I will merge it

**Comment by seths10** [comment]
> Can I add more

yes you can

**Comment by madfarizki** [comment]
Hi @seths10, I'v added some quotes, please check my pull request #9

**Comment by adityaacse** [comment]
Hi @seths10, I have added some quotes, please check my PR.

**Comment by HeYPoonam** [comment]
Hi @seths10 , I have added more quotes please accept my PR https://github.com/seths10/Quotes-Generator/pull/51

**Comment by seths10** [comment]
@HeYPoonam  and @adityaacse I've merged your commits

**Comment by animagus12** [comment]
Hey, Can I assist?

**Comment by seths10** [comment]
@animagus12 are u asking if you can add more quotes?

**Comment by darkling10** [comment]
Hiii,can I also add some quotes???

**Comment by Sathasivamthirumoorthi** [comment]
can i add some more quotes ?

**Comment by Vishal2002** [comment]
Instead of more quotes can we use Quotes API.

**Comment by TrlRizu** [comment]
Hey @seths10, I added 34 quotes and fixed indentations, and deleted 2 repeated quotes. I'd appreciate it if you merge my PR https://github.com/seths10/Quotes-Generator/pull/105

**Comment by seths10** [comment]
@Vishal2002  No please, we want beginners to be able to contribute to the repo. Using an API will limit that

**Comment by SnehaNarendran01071998** [comment]
hey @seths10, I have added another quote. Please review [the PR](https://github.com/seths10/Quotes-Generator/pull/136)

**Comment by Vishal2002** [comment]
Bro @seths10  Please review my PR and merge them.

**Comment by Vishal2002** [comment]
Bro Please merge the PR

**Comment by Ibadmoin** [comment]
Can I add more quotes and delete the repeated ones...

**Comment by seths10** [comment]
Yes you can @Ibadmoin

**Comment by MojoBoingo** [comment]
I'll add some more too.
