### ISSUE TITLE
Notification after copy

### ISSUE THREAD

**Issue by seths10** [seths10/Quotes-Generator#35]
Feature to show visual feedback that the quote has been copied to the clipboard

**Comment by VarunGitGood** [comment]
doing it

**Comment by VarunGitGood** [comment]
should i make a modal or ?

**Comment by YuriDevAT** [comment]
Hi @seths10 . I would love to work on this issue.

**Comment by seths10** [comment]
> should i make a modal or ?

feel free to do anything you want
