### ISSUE TITLE
Pop-up Notification After Copying Text

### ISSUE THREAD

**Issue by seths10** [seths10/Quotes-Generator#56]
I want you to modify the code to show a square pop-up notification at the bottom left of the page after a user clicks on the `copy to clipboard` button.

**Comment by beheradibas** [comment]
I would like to work on this.

**Comment by Abhay5855** [comment]
can you please assign me this issue?

**Comment by seths10** [comment]
@beheradibas @Abhay5855 I've assigned it to both of you, the first to submit a valid PR will be merged

**Comment by Aravind22** [comment]
@seths10 Sorry didn't ask first, last update in this thread was a week ago, so took it upon myself --> #115

**Comment by seths10** [comment]
sure, that's okay
