### ISSUE TITLE
Add more quotes in the quotes.js file

### ISSUE THREAD

**Issue by AnuragSharma122** [seths10/Quotes-Generator#69]
Please assign this issue to me. Also, add hactoberfest label to it.

**Comment by seths10** [comment]
I don't really understand the issue, can you explain it more?

**Comment by AnuragSharma122** [comment]
Hi @seths10, I edited the title of the issue.
Sorry for the typing mistake.

**Comment by AnuragSharma122** [comment]
Please assign and add hactoberfest label to it.

**Comment by seths10** [comment]
If you've made a PR, I will merge it.
